### ISSUE TITLE
Tensorflow serving support

### ISSUE THREAD

**Issue by tvlkmirzawidihananta** [tvlk-data/rm-cookiecutter-serving#23]
Tensorflow Serving has 2 service components:
- Serving server
for loading the model and do the inference
- Serving client
for preprocessing the request and postprocessing the response

So it needs 2 containers. But currently rmi only support 1 container. Is there any plan for supporting multiple container in the future? And what is the timeline?

References:
- https://medium.com/@tmlabonte/serving-image-based-deep-learning-models-with-tensorflow-servings-restful-api-d365c16a7dc4
- https://gist.githubusercontent.com/gauravkaila/ec6b12592e6c2103e8622292e83aecdd/raw/bc6afebb81cd0e774967d5cb23c46eed4a7fc0d1/client_template.py

P.S. different approach  is welcomed (if there is any 😬)

**Comment by tvlkmirzawidihananta** [comment]
@hadyan-tvlk, maybe can explain it better

**Comment by hadyan-tvlk** [comment]
Hi @eduardchai,

Just want to follow up this, is there any workaround solution to enable multi containers? thanks

**Comment by eduardchai** [comment]
@hadyan-tvlk added `additionalContainers` to helm chart: https://github.com/tvlk-data/rm-helm-charts/pull/23. You can use this to add additional container to the serving.

**Comment by hadyan-tvlk** [comment]
Cool, thanks @eduardchai, will play around with this tomorrow!

**Comment by hadyan-tvlk** [comment]
Hi @eduardchai , can we also enable `additionalContainersTemplate` to the rm helm chart?

I got info from Agung that this values in the future will replace `additionalContainers`. The only difference is `additionalContainersTemplate` can inject definitions from `values.yaml` while `additionalContainers` cannot. wdyt?

**Comment by eduardchai** [comment]
Sure, we can add that to rm helm chart. I'll let you know once i added it in.

**Comment by eduardchai** [comment]
@hadyan-tvlk option is added in this PR https://github.com/tvlk-data/rm-helm-charts/pull/25

**Comment by hadyan-tvlk** [comment]
Thanks @eduardchai!
